-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  user_role text NOT NULL,
  user_name text NOT NULL,
  action_type text NOT NULL CHECK (action_type = ANY (ARRAY['create'::text, 'read'::text, 'update'::text, 'delete'::text, 'login'::text, 'logout'::text, 'assign'::text, 'close'::text, 'approve'::text, 'reject'::text])),
  entity_type text NOT NULL,
  entity_id uuid,
  action_description text NOT NULL,
  old_value jsonb,
  new_value jsonb,
  ip_address inet,
  user_agent text,
  session_id text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.case_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL,
  leo_id uuid NOT NULL,
  station_id uuid NOT NULL,
  assigned_by uuid NOT NULL,
  assignment_method text DEFAULT 'manual'::text CHECK (assignment_method = ANY (ARRAY['manual'::text, 'auto'::text, 'emergency'::text])),
  priority text DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'emergency'::text])),
  assignment_notes text,
  status text DEFAULT 'assigned'::text CHECK (status = ANY (ARRAY['assigned'::text, 'accepted'::text, 'in_progress'::text, 'resolved'::text, 'reassigned'::text, 'closed'::text])),
  accepted_at timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  estimated_hours numeric,
  actual_hours numeric,
  deadline timestamp with time zone,
  assigned_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT case_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT case_assignments_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.crime_reports(id),
  CONSTRAINT case_assignments_leo_id_fkey FOREIGN KEY (leo_id) REFERENCES public.law_enforcement_officers(id),
  CONSTRAINT case_assignments_station_id_fkey FOREIGN KEY (station_id) REFERENCES public.police_stations(id),
  CONSTRAINT case_assignments_assigned_by_fkey FOREIGN KEY (assigned_by) REFERENCES public.station_admins(id)
);
CREATE TABLE public.case_closure_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL UNIQUE,
  closed_by uuid NOT NULL,
  closure_reason text NOT NULL CHECK (closure_reason = ANY (ARRAY['resolved'::text, 'insufficient_evidence'::text, 'false_report'::text, 'duplicate'::text, 'withdrawn'::text, 'other'::text])),
  closure_category text CHECK (closure_category = ANY (ARRAY['arrest_made'::text, 'case_solved'::text, 'case_dismissed'::text, 'referred_to_court'::text])),
  investigation_summary text NOT NULL,
  final_remarks text NOT NULL,
  actions_taken ARRAY,
  evidence_collected ARRAY,
  witnesses_interviewed integer DEFAULT 0,
  suspects_identified integer DEFAULT 0,
  arrests_made integer DEFAULT 0,
  fir_number text,
  court_case_number text,
  referred_to_court boolean DEFAULT false,
  court_name text,
  closure_document_url text,
  additional_documents jsonb DEFAULT '[]'::jsonb,
  closed_at timestamp with time zone DEFAULT now(),
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT case_closure_reports_pkey PRIMARY KEY (id),
  CONSTRAINT case_closure_reports_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.crime_reports(id),
  CONSTRAINT case_closure_reports_closed_by_fkey FOREIGN KEY (closed_by) REFERENCES public.law_enforcement_officers(id),
  CONSTRAINT case_closure_reports_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.station_admins(id)
);
CREATE TABLE public.case_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL,
  added_by uuid NOT NULL,
  added_by_role text NOT NULL,
  note_type text DEFAULT 'general'::text CHECK (note_type = ANY (ARRAY['general'::text, 'evidence'::text, 'witness'::text, 'suspect'::text, 'investigation'::text, 'internal'::text])),
  note_content text NOT NULL,
  is_internal boolean DEFAULT true,
  is_important boolean DEFAULT false,
  attachments jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT case_notes_pkey PRIMARY KEY (id),
  CONSTRAINT case_notes_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.crime_reports(id),
  CONSTRAINT case_notes_added_by_fkey FOREIGN KEY (added_by) REFERENCES public.users(id)
);
CREATE TABLE public.case_updates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid,
  updated_by uuid,
  old_status text NOT NULL,
  new_status text NOT NULL,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT case_updates_pkey PRIMARY KEY (id),
  CONSTRAINT case_updates_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.crime_reports(id),
  CONSTRAINT case_updates_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id)
);
CREATE TABLE public.crime_dataset (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  case_number text NOT NULL UNIQUE,
  category text NOT NULL,
  description text NOT NULL,
  location_address text,
  latitude double precision,
  longitude double precision,
  incident_date timestamp with time zone,
  province text,
  city text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crime_dataset_pkey PRIMARY KEY (id)
);
CREATE TABLE public.crime_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  case_number text UNIQUE,
  category text NOT NULL,
  description text NOT NULL,
  location_address text NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  incident_date timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'new'::text CHECK (status = ANY (ARRAY['new'::text, 'assigned'::text, 'in_progress'::text, 'closed'::text])),
  priority text NOT NULL DEFAULT 'medium'::text CHECK (priority = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'emergency'::text])),
  assigned_to uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  assigned_station_id uuid,
  province text,
  city text,
  CONSTRAINT crime_reports_pkey PRIMARY KEY (id),
  CONSTRAINT crime_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT crime_reports_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.users(id),
  CONSTRAINT crime_reports_assigned_station_id_fkey FOREIGN KEY (assigned_station_id) REFERENCES public.police_stations(id)
);
CREATE TABLE public.crimex_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  full_name text,
  email text UNIQUE,
  cnic text UNIQUE,
  phone text UNIQUE,
  role text NOT NULL,
  auth_uid uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crimex_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.criminal_records (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cnic text NOT NULL UNIQUE,
  full_name text NOT NULL,
  photo_url text,
  face_encoding text,
  offenses jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT criminal_records_pkey PRIMARY KEY (id)
);
CREATE TABLE public.evidence_files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_id uuid,
  file_name text NOT NULL,
  file_type text NOT NULL CHECK (file_type = ANY (ARRAY['image'::text, 'video'::text, 'audio'::text, 'document'::text])),
  file_url text NOT NULL,
  file_hash text NOT NULL,
  file_size bigint NOT NULL,
  uploaded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT evidence_files_pkey PRIMARY KEY (id),
  CONSTRAINT evidence_files_report_id_fkey FOREIGN KEY (report_id) REFERENCES public.crime_reports(id)
);
CREATE TABLE public.identifiers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  kind text NOT NULL CHECK (kind = ANY (ARRAY['email'::text, 'phone'::text, 'cnic'::text])),
  normalized_value text NOT NULL,
  table_name text NOT NULL,
  row_id text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT identifiers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.law_enforcement_officers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  station_id uuid NOT NULL,
  badge_number text NOT NULL UNIQUE CHECK (badge_number ~ '^\d{4}$'::text),
  cnic text NOT NULL UNIQUE CHECK (cnic ~ '^\d{13}$'::text),
  full_name text NOT NULL,
  email text UNIQUE,
  phone text NOT NULL,
  rank text NOT NULL DEFAULT 'Constable'::text,
  specialization ARRAY DEFAULT ARRAY['General'::text],
  max_active_cases integer DEFAULT 10,
  current_active_cases integer DEFAULT 0,
  total_cases_assigned integer DEFAULT 0,
  total_cases_closed integer DEFAULT 0,
  average_resolution_time_hours numeric DEFAULT 0,
  success_rate_percentage numeric DEFAULT 0,
  total_work_hours numeric DEFAULT 0,
  is_available boolean DEFAULT true,
  current_workload_status text DEFAULT 'low'::text CHECK (current_workload_status = ANY (ARRAY['low'::text, 'medium'::text, 'high'::text, 'overloaded'::text])),
  on_duty boolean DEFAULT true,
  shift_start time without time zone,
  shift_end time without time zone,
  permissions jsonb DEFAULT '{"close_cases": true, "view_evidence": true, "add_case_notes": true, "update_case_status": true, "generate_closure_report": true}'::jsonb,
  last_login timestamp with time zone,
  last_case_assigned timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  supervised_by uuid,
  password_hash text,
  CONSTRAINT law_enforcement_officers_pkey PRIMARY KEY (id),
  CONSTRAINT law_enforcement_officers_station_id_fkey FOREIGN KEY (station_id) REFERENCES public.police_stations(id),
  CONSTRAINT law_enforcement_officers_supervised_by_fkey FOREIGN KEY (supervised_by) REFERENCES public.station_admins(id)
);
CREATE TABLE public.leo_workload_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  leo_id uuid NOT NULL,
  active_cases integer NOT NULL,
  workload_status text NOT NULL,
  workload_percentage numeric NOT NULL,
  average_resolution_time_hours numeric,
  success_rate_percentage numeric,
  recorded_at timestamp with time zone DEFAULT now(),
  CONSTRAINT leo_workload_history_pkey PRIMARY KEY (id),
  CONSTRAINT leo_workload_history_leo_id_fkey FOREIGN KEY (leo_id) REFERENCES public.law_enforcement_officers(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  recipient_id uuid NOT NULL,
  recipient_role text NOT NULL,
  notification_type text NOT NULL CHECK (notification_type = ANY (ARRAY['case_assigned'::text, 'case_status_updated'::text, 'case_closed'::text, 'new_evidence'::text, 'deadline_approaching'::text, 'system_alert'::text, 'message'::text])),
  title text NOT NULL,
  message text NOT NULL,
  related_case_id uuid,
  related_user_id uuid,
  is_read boolean DEFAULT false,
  read_at timestamp with time zone,
  delivery_method ARRAY DEFAULT ARRAY['in_app'::text],
  sent_via_email boolean DEFAULT false,
  sent_via_push boolean DEFAULT false,
  priority text DEFAULT 'normal'::text CHECK (priority = ANY (ARRAY['low'::text, 'normal'::text, 'high'::text, 'urgent'::text])),
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_related_case_id_fkey FOREIGN KEY (related_case_id) REFERENCES public.crime_reports(id),
  CONSTRAINT notifications_related_user_id_fkey FOREIGN KEY (related_user_id) REFERENCES public.users(id),
  CONSTRAINT notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.users(id)
);
CREATE TABLE public.police_stations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  station_code text NOT NULL UNIQUE,
  station_name text NOT NULL,
  address text NOT NULL,
  city text NOT NULL,
  province text NOT NULL,
  latitude numeric NOT NULL,
  longitude numeric NOT NULL,
  phone text NOT NULL,
  email text,
  officer_in_charge text,
  jurisdiction_radius_km numeric DEFAULT 10.0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT police_stations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.station_admins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  station_id uuid NOT NULL,
  badge_number text NOT NULL UNIQUE CHECK (badge_number ~ '^\d{4}$'::text),
  cnic text NOT NULL UNIQUE CHECK (cnic ~ '^\d{13}$'::text),
  full_name text NOT NULL,
  email text UNIQUE,
  phone text NOT NULL,
  rank text NOT NULL DEFAULT 'Inspector'::text,
  permissions jsonb DEFAULT '{"manage_leos": true, "assign_cases": true, "view_analytics": true, "generate_reports": true, "view_station_cases": true}'::jsonb,
  max_supervised_leos integer DEFAULT 20,
  last_login timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  appointed_by uuid,
  password_hash text,
  CONSTRAINT station_admins_pkey PRIMARY KEY (id),
  CONSTRAINT station_admins_station_id_fkey FOREIGN KEY (station_id) REFERENCES public.police_stations(id),
  CONSTRAINT station_admins_appointed_by_fkey FOREIGN KEY (appointed_by) REFERENCES public.system_admins(id)
);
CREATE TABLE public.station_analytics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  station_id uuid NOT NULL,
  date date NOT NULL,
  total_cases_received integer DEFAULT 0,
  total_cases_assigned integer DEFAULT 0,
  total_cases_in_progress integer DEFAULT 0,
  total_cases_closed integer DEFAULT 0,
  total_emergency_cases integer DEFAULT 0,
  average_assignment_time_hours numeric DEFAULT 0,
  average_resolution_time_hours numeric DEFAULT 0,
  average_response_time_minutes numeric DEFAULT 0,
  total_active_leos integer DEFAULT 0,
  average_leo_workload_percentage numeric DEFAULT 0,
  case_closure_rate numeric DEFAULT 0,
  citizen_satisfaction_score numeric,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT station_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT station_analytics_station_id_fkey FOREIGN KEY (station_id) REFERENCES public.police_stations(id)
);
CREATE TABLE public.system_admins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid UNIQUE,
  cnic text NOT NULL UNIQUE CHECK (cnic ~ '^\d{13}$'::text),
  full_name text NOT NULL,
  email text UNIQUE,
  phone text NOT NULL,
  is_super_admin boolean DEFAULT false,
  permissions jsonb DEFAULT '{"manage_leos": true, "manage_users": true, "view_all_cases": true, "manage_stations": true, "manage_criminal_db": true}'::jsonb,
  last_login timestamp with time zone,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  password_hash text,
  CONSTRAINT system_admins_pkey PRIMARY KEY (id),
  CONSTRAINT system_admins_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.system_admins(id)
);
CREATE TABLE public.system_settings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  setting_key text NOT NULL UNIQUE,
  setting_value jsonb NOT NULL,
  setting_type text NOT NULL,
  description text,
  is_public boolean DEFAULT false,
  updated_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (id),
  CONSTRAINT system_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.system_admins(id)
);
CREATE TABLE public.user_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  session_token text NOT NULL UNIQUE,
  refresh_token text UNIQUE,
  device_info jsonb,
  ip_address inet,
  user_agent text,
  is_active boolean DEFAULT true,
  last_activity timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  logged_out_at timestamp with time zone,
  CONSTRAINT user_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT user_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  firebase_uid text UNIQUE,
  cnic text UNIQUE,
  full_name text,
  email text NOT NULL UNIQUE,
  phone text,
  role text NOT NULL DEFAULT 'citizen'::text CHECK (role = ANY (ARRAY['citizen'::text, 'system_admin'::text, 'station_admin'::text, 'leo'::text])),
  profile_image_url text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id)
);
